// The following code is licensed under the GNU General Public License v3.0
// Please see the README for more complete documentation of the indicator and how it works
// © EFRAN1812
//@version=5

// Set indicator title and input values
indicator(title="VWAP Percent Distance", shorttitle="VWAP %D")
MALength = input(14) // Set how many candles back will be inputted into the moving average

// Compute the distance between the current price and VWAP values
vwap = ta.vwap
price_vwap_dist = close - vwap
relative_vwap_dist = (price_vwap_dist / vwap) * 100

// Plot the data
hline(0, "Mid Line", color=color.new(#787B86, 50)) // Plots a neutral line at 0 as a reference
plot(relative_vwap_dist, color=color.aqua) // VWAP %D plot
plot(ta.sma(relative_vwap_dist, MALength), color=color.lime) // VWAP %D moving average plot